config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :dashboard, only: %i[index]
  resources :personal_infos
  resources :academic_infos
  resources :courses
  resources :experiences
  resources :skills
  resources :projects
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name_skill, presence: true
  validates :type_skill, presence: true

  enum type_skill: { Soft: 0, Hard: 1 }
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    return redirect_to skill_path(@skill) if @skill.save

    render :new
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    return redirect_to skill_path(@skill) if @skill.update(skill_params)

    render :edit
  end

  def destroy
    @skills = Skill.all
    @skill = Skill.find(params[:id]) if exists_data
    return redirect_to skills_path if exists_data && @skill.delete

    flash.now[:alert] = t(:non_existing_data).capitalize
    render :index
  end

  private

  def skill_params
    params.require(:skill).permit(:name_skill, :type_skill)
  end
end

def exists_data
  Skill.exists?(params[:id])
end

app/views/skills/edit.html.erb
<p><%= link_to t(:return).capitalize, skills_path %></p>

<h3><%= t(:edit_skills).capitalize %></h3>

<% if @skill.errors.any? %>
  <% @skill.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @skill, local: true do |f| %>

  <%= f.label :name_skill, t(:name_skill).capitalize %>
  <%= f.text_field :name_skill %>

  <%= f.label :type_skill, t(:type_skill).capitalize %>
  <%= f.select(:type_skill, [:Soft, :Hard], {include_blank: ''}, { :style => '' }) %>

  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/skills/index.html.erb
<%= link_to t(:return).capitalize, dashboard_index_path %>

<h2><%= t(:skills) %></h2>

<%= link_to t(:add_new_date).capitalize, new_skill_path %>

<% @skills.each do |skill| %>

  <p><%= skill.name_skill %></p>
  <p><%= skill.type_skill %></p>

  <%= link_to(t(:edit).capitalize, edit_skill_path(skill), id: "skill_n_#{skill.id}") %>
	<%= link_to(t(:delete).capitalize, skill_path(skill), id: "skill_d_#{skill.id}", method: :delete) %>
<% end %>

app/views/skills/new.html.erb
<p><%= link_to t(:return).capitalize, skills_path %></p>

<h3><%= t(:add_skills) %></h3>

<% if @skill.errors.any? %>
  <% @skill.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @skill, local: true do |f| %>

  <%= f.label :name_skill, t(:name_skill).capitalize %>
  <%= f.text_field :name_skill %>

  <%= f.label :type_skill, t(:type_skill).capitalize %>
  <%= f.select(:type_skill, [:Soft, :Hard], {include_blank: ''}, { :style => '' }) %>

  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/skills/show.html.erb
<p><%= link_to t(:return).capitalize, skills_path %></p>

<h5><%= t(:details).capitalize %></h5>

<p><%= @skill.name_skill %></p>
<p><%= @skill.type_skill %></p>