config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :dashboard, only: %i[index]
  resources :personal_infos
  resources :academic_infos
  resources :courses
  resources :experiences
  resources :skills
  resources :projects
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name_project, presence: true
  validates :description_project, presence: true
  validates :link_project, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    return redirect_to project_path(@project) if @project.save

    render :new
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    return redirect_to project_path(@project) if @project.update(project_params)

    render :edit
  end

  def destroy
    @projects = Project.all
    @project = Project.find(params[:id]) if exists_data
    return redirect_to projects_path if exists_data && @project.delete

    flash.now[:alert] = t(:non_existing_data).capitalize
    render :index
  end

  private

  def project_params
    params.require(:project).permit(:name_project, :description_project,
                                    :link_project, :img_project)
  end

  def exists_data
    Project.exists?(params[:id])
  end
end

app/views/projects/edit.html.erb
<p><%= link_to t(:return).capitalize, projects_path %></p>

<h3><%= t(:edit_project.capitalize) %></h3>

<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @project, local: true do |f| %>

  <%= f.label :name_project, t(:name_project).capitalize %>
  <%= f.text_field :name_project %>

  <%= f.label :description_project, t(:description_project).capitalize %>
  <%= f.text_field :description_project %>

  <%= f.label :link_project, t(:link_project).capitalize %>
  <%= f.url_field :link_project %>

  <%= f.label :img_project, t(:img_project).capitalize %>
  <%= f.url_field :img_project %>

  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/projects/index.html.erb
<%= link_to t(:return).capitalize, dashboard_index_path %>

<h2><%= t(:projects) %></h2>

<%= link_to t(:add_new_date).capitalize, new_project_path %>

<% @projects.each do |project| %>
  <p><%= project.name_project %></p>
  <p><%= project.description_project %></p>
  <p><%= project.link_project %></p>
  <p><%= image_tag(project.img_project) %></p>
  
  <%= link_to(t(:edit).capitalize, edit_project_path(project), id: "project_e_#{project.id}") %>
	<%= link_to(t(:delete).capitalize, project_path(project), id: "project_d_#{project.id}", method: :delete) %>
<% end %>

app/views/projects/new.html.erb
<p><%= link_to t(:return).capitalize, projects_path %></p>

<h3><%= t(:add_projects) %></h3>

<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @project, local: true do |f| %>

  <%= f.label :name_project, t(:name_project).capitalize %>
  <%= f.text_field :name_project %>

  <%= f.label :description_project, t(:description_project).capitalize %>
  <%= f.text_field :description_project %>

  <%= f.label :link_project, t(:link_project).capitalize %>
  <%= f.url_field :link_project %>

  <%= f.label :img_project, t(:img_project).capitalize %>
  <%= f.url_field :img_project %>

  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/projects/show.html.erb
<p><%= link_to t(:return).capitalize, projects_path %></p>

<h5><%= t(:details).capitalize %></h5>

<p><%= @project.name_project %></p>
<p><%= @project.description_project %></p>
<p><%= @project.link_project %></p>
<p><%= image_tag(@project.img_project) %></p>