config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :dashboard, only: %i[index]
  resources :personal_infos
  resources :academic_infos
  resources :courses
  resources :experiences
  resources :skills
  resources :projects
end

app/models/experience.rb
class Experience < ApplicationRecord
  validates :occupation, presence: true
  validates :description_occupation, presence: true
  validates :company, presence: true
  validates :start_experience, presence: true
  validates :check_work, presence: true

  enum check_work: { Sim: 0, Não: 1 }
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @experiences = Experience.all
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    return redirect_to experience_path(@experience) if @experience.save

    render :new
  end

  def show
    @experience = Experience.find(params[:id])
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    @experience = Experience.find(params[:id])
    if @experience.update(experience_params)
      return redirect_to experience_path(@experience)
    end

    render :edit
  end

  def destroy
    @experiences = Experience.all
    @experience = Experience.find(params[:id]) if exists_data
    return redirect_to experiences_path if exists_data && @experience.delete

    flash.now[:alert] = t(:non_existing_data).capitalize
    render :index
  end

  private

  def experience_params
    params.require(:experience).permit(:occupation, :description_occupation,
                                       :company, :start_experience,
                                       :end_experience, :check_work)
  end

  def exists_data
    Experience.exists?(params[:id])
  end
end

app/views/experiences/edit.html.erb
<p><%= link_to t(:return).capitalize, experience_path %></p>

<h3><%= t(:edit_experience).capitalize %></h3>

<% if @experience.errors.any? %>
  <% @experience.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @experience, local: true do |f| %>

  <%= f.label :occupation, t(:occupation).capitalize %>
  <%= f.text_field :occupation %>

  <%= f.label :description_occupation, t(:description_occupation).capitalize %>
  <%= f.text_field :description_occupation %>

  <%= f.label :company, t(:company).capitalize %>
  <%= f.text_field :company %>

  <%= f.label :start_experience, t(:start_experience).capitalize %>
  <%= f.date_field :start_experience %>

  <%= f.label :end_experience, t(:end_experience).capitalize %>
  <%= f.date_field :end_experience %>

  <%= f.label :check_work, t(:check_work).capitalize %>
  <%= f.select(:check_work, [:Sim, :Não], {include_blank: ''}, { :style => '' }) %>

  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/experiences/index.html.erb
<%= link_to t(:return).capitalize, dashboard_index_path %>

<h2><%= t(:experiences) %></h2>

<%= link_to t(:add_new_date).capitalize, new_experience_path %>

<% @experiences.each do |experience|%>

  <p><%= experience.occupation %></p>
  <p><%= experience.description_occupation %></p>
  <p><%= experience.company %></p>
  <p><%= experience.start_experience %></p>
  <p><%= experience.end_experience %></p>
  <p><%= experience.check_work %></p>

  <%= link_to(t(:edit).capitalize, edit_experience_path(experience), id: "experience_e_#{experience.id}") %>
	<%= link_to(t(:delete).capitalize, experience_path(experience), id: "experience_d_#{experience.id}", method: :delete) %>
<% end %>

app/views/experiences/new.html.erb
<p><%= link_to t(:return).capitalize, experiences_path %></p>

<h3><%= t(:add_experiences) %></h3>

<% if @experience.errors.any? %>
  <% @experience.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @experience, local: true do |f| %>

  <%= f.label :occupation, t(:occupation).capitalize %>
  <%= f.text_field :occupation %>

  <%= f.label :description_occupation, t(:description_occupation).capitalize %>
  <%= f.text_field :description_occupation %>

  <%= f.label :company, t(:company).capitalize %>
  <%= f.text_field :company %>

  <%= f.label :start_experience, t(:start_experience).capitalize %>
  <%= f.date_field :start_experience %>

  <%= f.label :end_experience, t(:end_experience).capitalize %>
  <%= f.date_field :end_experience %>

  <%= f.label :check_work, t(:check_work).capitalize %>
  <%= f.select(:check_work, [:Sim, :Não], {include_blank: ''}, { :style => '' }) %>
  
  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/experiences/show.html.erb
<p><%= link_to t(:return).capitalize, experiences_path %></p>

<h5><%= t(:details).capitalize %></h5>

<p><%= @experience.occupation %></p>
<p><%= @experience.description_occupation %></p>
<p><%= @experience.company %></p>
<p><%= @experience.start_experience %></p>
<p><%= @experience.end_experience %></p>
<p><%= @experience.check_work %></p>