config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :dashboard, only: %i[index]
  resources :personal_infos
  resources :academic_infos
  resources :courses
  resources :experiences
  resources :skills
  resources :projects
end

app/models/academic_info.rb
class AcademicInfo < ApplicationRecord
  validates :name_academic, presence: true
  validates :description_academic, presence: true
  validates :institution_academic, presence: true
  validates :conclusion_academic, presence: true
  validates :start_date, presence: true

  enum conclusion_academic: { Cursando: 0, Concluido: 1 }
end

app/controllers/academic_infos_controller.rb
class AcademicInfosController < ApplicationController
  before_action :authenticate_admin!

  def index
    @academic_infos = AcademicInfo.all
  end

  def new
    @academic_info = AcademicInfo.new
  end

  def create
    @academic_info = AcademicInfo.new(academic_info_params)
    return redirect_to academic_info_path(@academic_info) if @academic_info.save

    render :new
  end

  def show
    @academic_info = AcademicInfo.find(params[:id])
  end

  def edit
    @academic_info = AcademicInfo.find(params[:id])
  end

  def update
    @academic_info = AcademicInfo.find(params[:id])
    if @academic_info.update(academic_info_params)
      return redirect_to academic_info_path(@academic_info)
    end

    render :edit
  end

  def destroy
    @academic_infos = AcademicInfo.all
    @academic_info = AcademicInfo.find(params[:id]) if exists_data
    if exists_data && @academic_info.delete
      return redirect_to academic_infos_path
    end

    flash.now[:alert] = t(:non_existing_data).capitalize
    render :index
  end

  private

  def academic_info_params
    params.require(:academic_info).permit(:name_academic, :description_academic,
                                          :institution_academic, :start_date,
                                          :conclusion_academic, :end_date)
  end

  def exists_data
    AcademicInfo.exists?(params[:id])
  end
end

app/views/academic_infos/edit.html.erb
<p><%= link_to t(:return).capitalize, academic_infos_path %></p>

<h3><%= t(:edit_academic_infos).capitalize %></h3>

<% if @academic_info.errors.any? %>
  <% @academic_info.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @academic_info, local: true do |f| %>
  <%= f.label :name_academic, t(:name_academic).capitalize %>
  <%= f.text_field :name_academic %>

  <%= f.label :institution_academic, t(:institution_academic).capitalize %>
  <%= f.text_field :institution_academic %>

  <%= f.label :start_date, t(:start_date).capitalize %>
  <%= f.date_field :start_date %>

  <%= f.label :end_date, t(:end_date).capitalize %>
  <%= f.date_field :end_date %>

  <%= f.label :conclusion_academic, t(:conclusion_academic).capitalize %>
  <%= f.select(:conclusion_academic, [:Cursando, :Concluido], {include_blank: ''}, { :style => '' }) %>

  <%= f.label :description_academic, t(:description_academic).capitalize %>
  <%= f.text_field :description_academic %>
  
  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/academic_infos/index.html.erb
<%= link_to t(:return), dashboard_index_path %>

<h2><%= t(:academic_infos) %></h2>

<%= link_to t(:add_new_date).capitalize, new_academic_info_path %>

<% @academic_infos.each do |academic_info| %>
  <p><%= academic_info.name_academic %></p>
  <p><%= academic_info.institution_academic %></p>
  <p><%= academic_info.start_date %></p>
  <p><%= academic_info.end_date %></p>
  <p><%= academic_info.conclusion_academic %></p>
  <p><%= academic_info.description_academic %></p>

  <%= link_to(t(:edit).capitalize, edit_academic_info_path(academic_info), id: "academic_n_#{academic_info.id}") %> 
	<%= link_to(t(:delete).capitalize, academic_info_path(academic_info), id: "academic_d_#{academic_info.id}", method: :delete) %>
<% end %>

app/views/academic_infos/new.html.erb
<p><%= link_to t(:return).capitalize, academic_infos_path %></p>

<h3><%= t(:add_academic_infos) %></h3>

<% if @academic_info.errors.any? %>
  <% @academic_info.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @academic_info, local: true do |f| %>
  <%= f.label :name_academic, t(:name_academic).capitalize %>
  <%= f.text_field :name_academic %>

  <%= f.label :institution_academic, t(:institution_academic).capitalize %>
  <%= f.text_field :institution_academic %>

  <%= f.label :start_date, t(:start_date).capitalize %>
  <%= f.date_field :start_date %>

  <%= f.label :end_date, t(:end_date).capitalize %>
  <%= f.date_field :end_date %>

  <%= f.label :conclusion_academic, t(:conclusion_academic).capitalize %>
  <%= f.select(:conclusion_academic, [:Cursando, :Concluido], {include_blank: ''}, { :style => '' }) %>

  <%= f.label :description_academic, t(:description_academic).capitalize %>
  <%= f.text_field :description_academic %>

  <%= f.submit t(:save).capitalize %>
<% end %>

app/views/academic_infos/show.html.erb
<p><%= link_to t(:return).capitalize, academic_infos_path %></p>

<h5><%= t(:details).capitalize %></h5>

<p><%= @academic_info.name_academic %></p>
<p><%= @academic_info.institution_academic %></p>
<p><%= @academic_info.start_date %></p>
<p><%= @academic_info.end_date %></p>
<p><%= @academic_info.conclusion_academic %></p>
<p><%= @academic_info.description_academic %></p>